project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - schedule/*.qmd
    - slides/*.qmd
  resources:
    - img/
    - css/
    - slides/
    - schedule/
    - codes/


website:
  title: "Introduction to R"
  site-url: https://sichaow58.github.io/Introduction-To-R/
  google-analytics: G-68JBPLLNLG
  page-footer: >
      This workshop has been developed by statisticians of CSTAT at Michigan State University [CSTAT](https://cstat.msu.edu/)
  
  
  navbar:
    left:
      - text: "Schedule"
        href: schedule/schedule.qmd
      - text: "Workshop Materials"
        href: codes/Intro-to-R.html
      - text: "Slides"
        href: slides/Intro2R.html
    right:
      - text: "CSTAT"
        href: https://cstat.msu.edu/
      - text: "GitHub"
        href: https://github.com/SichaoW58/Introduction-To-R
          

format:
  html:
    theme: simplex
    css: css/styles.css
    fig-align: "center"
    toc: true
    number-sections: false
    code-block-bg: true
    code-copy: true      # enables copy button (default in most themes)
    code-tools: false    # hide the source-code tools panel on pages
    code-line-wrap: wrap
    prompt: true         
    self-contained: true


# Global Execution Defaults
execute:
  echo: false               # show code
  eval: false              # keep site build lightweight; codes are published as materials
  warning: false           # show warnings
  error: false             # show errors
  message: false           # show messages
  prompt: true
