---
sidebar: false
toc: false
execute:
  echo: false
  warning: false
  message: false
---

# Introduction to R

| Audience   | Computational skills required | Duration                                                   |
|:---------------------|:---------------------------|:---------------------|
| Researchers | None                          | 3 hours |

### Description

This repository has teaching materials for a hands-on **Introduction to R** as 2 days lessons. The workshop will introduce participants to the basics of R and RStudio. R is a simple programming environment that enables the effective handling of data, while providing excellent graphical support. RStudio is a tool that provides a user-friendly environment for working with R. These materials are intended to provide both basic R programming knowledge and its application for increasing efficiency for data analysis.

**Note for participants:** No prior experience with R is required for this workshop. We will walk through the hands-on exercises together. No need to preview the materials before the workshop.

### Learning Objectives

1. **R and R Studio:** Familiarize with R and RStudio and navigate the RStudio.
2. **R data types and structures:** Understand the frequently-used data types and data structures in R.
3. **Data manipulation essentials:** Demonstrate the use of functions for wrangling data from various data structures.
4. **Data visualization (Optional):** Simple visualization using the ggplot2 package.

### Materials

- [Workshop schedule](schedule/schedule.qmd)
- [Code source (Quarto)](codes/Intro-to-R.qmd)
- [Code source (R Markdown)](codes/Intro-to-R.Rmd)


### Installation Requirements

Please install R and RStudio before the 'Introduction to R For Researchers' workshop. Ensure that both programs are running correctly on your machine. If you encounter any technical difficulties during the installation, please contact the IT department within your specific department for assistance.

### Installing R

It is straightforward installing R on your machine. Follow these steps:

1.	Go to the CRAN (Comprehensive R Archive Network) [R website](https://cran.r-project.org/).
2.	Choose to download R for Linux, Mac or Windows. Latest version: R-4.6.0 (released on 2026-04-24, Because it was There).
3.	For Windows users, just install ‘base’ and this will link you to the download file.
4.	For Mac users, make sure you download the right version for your CPU.


### Installing RStudio
RStudio is the most popular integrated development environment (IDE) for R. It makes working with R easier, more productive, and organized, especially for new users. Follow these steps:


1.	Go to the RStudio download website [(Posit)](https://posit.co/download/rstudio-desktop/).
2.	Choose the ‘Installers for your system’ to download
3.	Install RStudio as per the instructions.

### Dataset

All files used for this workshop are available here:

- [ABM CSV data](codes/abm_short.csv)
- [ABM RDS data](codes/dat_abm.rds)


